local k = vim.keymap.set
-- DAP
k('n', '<Leader>d<F5>', function() require('dap').continue() end)
k('n', '<Leader>d<F6>', function() require('dap').step_over() end)
k('n', '<Leader>d<F7>', function() require('dap').step_into() end)
k('n', '<Leader>d<F8>', function() require('dap').step_out() end)
k('n', '<Leader>db', function() require('dap').toggle_breakpoint() end)
k('n', '<Leader>dr', function() require('dap').repl.open() end)
k('n', '<Leader>dl', function() require('dap').run_last() end)
k({'n', 'v'}, '<Leader>dh', function()
require('dap.ui.widgets').hover()
end)
k({'n', 'v'}, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end)
k('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end)
k('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end)
