local dap = require('dap')
local widgets = require('dap.ui.widgets')
local k = vim.keymap.set
-- DAP
k('n', '<Leader>d<F5>', function() dap.continue() end)
k('n', '<Leader>d<F6>', function() dap.step_over() end)
k('n', '<Leader>d<F7>', function() dap.step_into() end)
k('n', '<Leader>d<F8>', function() dap.step_out() end)
k('n', '<Leader>db', function() dap.toggle_breakpoint() end)
k('n', '<Leader>dr', function() dap.repl.open() end)
k('n', '<Leader>dl', function() dap.run_last() end)
k({'n', 'v'}, '<Leader>dh', function() widgets.hover() end)
k({'n', 'v'}, '<Leader>dp', function() widgets.preview() end)
k('n', '<Leader>df', function() widgets.centered_float(widgets.frames) end)
k('n', '<Leader>ds', function() widgets.centered_float(widgets.scopes) end)
