local dap = require("dap")
local widgets = require("dap.ui.widgets")
local k = vim.api.nvim_set_keymap
k("n", "<F5>", function()
	dap.continue()
end)
k("n", "<F6>", function()
	dap.step_over()
end)
k("n", "<F7>", function()
	dap.step_into()
end)
k("n", "<F8>", function()
	dap.step_out()
end)
k("n", "<leader>db", function()
	dap.toggle_breakpoint()
end)
k("n", "<leader>dr", function()
	dap.repl.open()
end)
k("n", "<leader>dl", function()
	dap.run_last()
end)
k({ "n", "v" }, "<leader>dh", function()
	widgets.hover()
end)
k({ "n", "v" }, "<leader>dp", function()
	widgets.preview()
end)
k("n", "<leader>df", function()
	widgets.centered_float(widgets.frames)
end)
k("n", "<leader>ds", function()
	widgets.centered_float(widgets.scopes)
end)
