vim.api.nvim_set_hl(0, "NvimLightGrey1", { fg = "#eef1f8" })
vim.api.nvim_set_hl(0, "NvimLightGrey2", { fg = "#e0e2ea" })
vim.api.nvim_set_hl(0, "NvimLightGrey3", { fg = "#c4c6cd" })
vim.api.nvim_set_hl(0, "NvimDarkGrey1", { fg = "#07080d" })
vim.api.nvim_set_hl(0, "NvimDarkGrey2", { fg = "#14161b" })
vim.api.nvim_set_hl(0, "NvimDarkGrey3", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "NvimDarkGrey4", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "NvimLightRed", { fg = "#ffc0b9" })
vim.api.nvim_set_hl(0, "NvimLightGreen", { fg = "#b3f6c0" })
vim.api.nvim_set_hl(0, "NvimLightYellow", { fg = "#fce094" })
vim.api.nvim_set_hl(0, "NvimLightBlue", { fg = "#a6dbff" })
vim.api.nvim_set_hl(0, "NvimLightMagenta", { fg = "#ffcaff" })
vim.api.nvim_set_hl(0, "NvimLightCyan", { fg = "#8cf8f7" })

vim.api.nvim_set_hl(0, "Keyword", { fg = "NvimLightMagenta", bold = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "NvimLightCyan" })
vim.api.nvim_set_hl(0, "Type", { fg = "NvimLightYellow" })
vim.api.nvim_set_hl(0, "Function", { fg = "NvimLightBlue" })
vim.api.nvim_set_hl(0, "Special", { fg = "NvimLightRed" })

vim.api.nvim_set_hl(0, "@module.rust", { fg = "NvimLightRed" })
vim.api.nvim_set_hl(0, "@attribute.python", { fg = "NvimLightMagenta" })
