return {
    cmd = { "typescript-language-server", "--stdio" },
    settings = {
        typescript = {
            format = {
                allowIncompleteCompletions = false,
                allowRenameOfImportPath = true,
                insertSpaceAfterCommaDelimiter = true,
                insertSpaceAfterSemicolonInForStatements = true,
                insertSpaceBeforeAndAfterBinaryOperators = true,
                insertSpaceAfterConstructor = true,
                insertSpaceAfterKeywordsInControlFlowStatements = true,
                insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
                insertSpaceAfterOpeningAndBeforeClosingEmptyBraces = true,
                insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = false,
                insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = false,
                insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true,
                insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = true,
                insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = true,
                insertSpaceAfterTypeAssertion = true,
                insertSpaceBeforeFunctionParenthesis = false,
                placeOpenBraceOnNewLineForFunctions = false,
                placeOpenBraceOnNewLineForControlBlocks = false,
                insertSpaceBeforeTypeAnnotation = false,
                semicolons = "insert",
            },
        },
    },
    single_file_support = true,
}
